module.exports = {
  apps: [
    {
      name: 'scum-bot',
      script: 'src/bot.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        BOT_ENABLE_SCUM_WEBHOOK: 'true',
        BOT_ENABLE_RESTART_SCHEDULER: 'true',
        BOT_ENABLE_ADMIN_WEB: 'false',
        BOT_ENABLE_RENTBIKE_SERVICE: 'false',
        BOT_ENABLE_DELIVERY_WORKER: 'false',
        BOT_ENABLE_OPS_ALERT_ROUTE: 'true',
      },
    },
    {
      name: 'scum-worker',
      script: 'src/worker.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        WORKER_ENABLE_RENTBIKE: 'true',
        WORKER_ENABLE_DELIVERY: 'true',
        WORKER_HEARTBEAT_MS: '60000',
      },
    },
    {
      name: 'scum-watcher',
      script: 'scum-log-watcher.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
      },
    },
    {
      name: 'scum-web-portal',
      script: 'apps/web-portal-standalone/server.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        WEB_PORTAL_SECURE_COOKIE: 'true',
        WEB_PORTAL_ENFORCE_ORIGIN_CHECK: 'true',
      },
    },
  ],
};
